config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/hython-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/hython-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-ochre-chimpanzee.sh
        container: qc.acc_crappy-chartreuse-hyrax
  QC.Doc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-emerald-tamarin.sh
        container: qc.doc_thirsty-ultramarine-beetle
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-cyan-bandicoot.sh
        container: qc.doc_dorky-plum-frigatebird
      github.com/interTwin-eu/hython-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-charcoal-paradise.sh
        container: qc.doc_bumpy-gamboge-ocelot
  QC.Lic:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-wheat-bear.sh
        container: qc.lic_chummy-eggplant-wombat
  QC.Met:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-goldenrod-schnauzer.sh
        container: qc.met_smelly-corn-coyote
  QC.Sec:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-apricot-squirrel.sh
        container: qc.sec_crabby-olive-capybara
  QC.Sty:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-wheat-husky.sh
        container: qc.sty_snoopy-fuchsia-chimpanzee
      github.com/interTwin-eu/hython-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-heliotrope-avocet.sh
        container: qc.sty_queasy-violet-frise
      github.com/interTwin-eu/hython-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-beige-gopher.sh
        container: qc.sty_cheeky-harlequin-emu
  QC.Uni:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-wisteria-kangaroo.sh
        container: qc.uni_lumpy-jade-wildebeest
  QC.Ver:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-tomato-walrus.sh
        container: qc.ver_muggy-denim-mule
timeout: 5400
