config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/hython-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/hython-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-ochre-hamster.sh
        container: qc.acc_zippy-peach-dhole
  QC.Doc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-orange-whippet.sh
        container: qc.doc_wimpy-flax-wrasse
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-cobalt-bird.sh
        container: qc.doc_beady-harlequin-caracal
      github.com/interTwin-eu/hython-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-harlequin-budgerigar.sh
        container: qc.doc_sleazy-celadon-fish
  QC.Lic:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-turquoise-newfoundland.sh
        container: qc.lic_sloppy-orange-chimpanzee
  QC.Met:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-saffron-mule.sh
        container: qc.met_surly-taupe-wombat
  QC.Sec:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-white-paradise.sh
        container: qc.sec_muzzy-olive-grouse
  QC.Sty:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-magnolia-mandrill.sh
        container: qc.sty_blurry-copper-rottweiler
      github.com/interTwin-eu/hython-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-lilac-chow.sh
        container: qc.sty_thirsty-fuchsia-cichlid
      github.com/interTwin-eu/hython-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-amaranth-bombay.sh
        container: qc.sty_skinny-celadon-hyena
  QC.Uni:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-sapphire-bear.sh
        container: qc.uni_tasty-lavender-woodpecker
  QC.Ver:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-chartreuse-wallaby.sh
        container: qc.ver_pasty-bistre-tortoise
timeout: 5400
