config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/hython-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/hython-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-azure-cockroach.sh
        container: qc.acc_muzzy-peach-chicken
  QC.Doc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-saffron-birman.sh
        container: qc.doc_leaky-rust-scorpion
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-eggplant-balinese.sh
        container: qc.doc_cloudy-taupe-spitz
      github.com/interTwin-eu/hython-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-asparagus-sparrow.sh
        container: qc.doc_shabby-cream-molly
  QC.Lic:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.messy-champagne-quokka.sh
        container: qc.lic_smelly-salmon-chinchilla
  QC.Met:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-azure-chinchilla.sh
        container: qc.met_woolly-bistre-macaw
  QC.Sec:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-sapphire-cougar.sh
        container: qc.sec_wimpy-maroon-macaw
  QC.Sty:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-wheat-hound.sh
        container: qc.sty_seedy-ivory-mastiff
      github.com/interTwin-eu/hython-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-cornflower-emu.sh
        container: qc.sty_lanky-wisteria-seal
      github.com/interTwin-eu/hython-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-fuchsia-wolfhound.sh
        container: qc.sty_shaggy-lime-antelope
  QC.Uni:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-vermilion-kakapo.sh
        container: qc.uni_woolly-cardinal-flounder
  QC.Ver:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-magnolia-kangaroo.sh
        container: qc.ver_smelly-peach-tarantula
timeout: 5400
