config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/hython-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/hython-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-salmon-hummingbird.sh
        container: qc.acc_fuzzy-copper-ostrich
  QC.Doc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-amaranth-okapi.sh
        container: qc.doc_muggy-razzmatazz-mastiff
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-beige-cow.sh
        container: qc.doc_randy-corn-audemer
      github.com/interTwin-eu/hython-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-firebrick-crocodile.sh
        container: qc.doc_flaky-champagne-gorilla
  QC.Lic:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-ochre-skunk.sh
        container: qc.lic_wheezy-beige-caterpillar
  QC.Met:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-apricot-bullfrog.sh
        container: qc.met_bumpy-goldenrod-buffalo
  QC.Sec:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-cerulean-spaniel.sh
        container: qc.sec_silly-lime-dhole
  QC.Sty:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-denim-hare.sh
        container: qc.sty_lovely-firebrick-discus
      github.com/interTwin-eu/hython-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-azure-chipmunk.sh
        container: qc.sty_slimy-chartreuse-ibis
      github.com/interTwin-eu/hython-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-chestnut-guppy.sh
        container: qc.sty_baggy-amethyst-seahorse
  QC.Uni:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-periwinkle-deer.sh
        container: qc.uni_ready-maroon-barracuda
  QC.Ver:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-persimmon-chinook.sh
        container: qc.ver_sleepy-alizarin-oriole
timeout: 5400
