config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/hython-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/hython-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-rose-hyrax.sh
        container: qc.acc_gamy-denim-collie
  QC.Doc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-ivory-raccoon.sh
        container: qc.doc_jumpy-crimson-schnauzer
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-blue-bulldog.sh
        container: qc.doc_tacky-amaranth-newt
      github.com/interTwin-eu/hython-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-green-squid.sh
        container: qc.doc_pasty-blue-spaniel
  QC.Lic:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-copper-javanese.sh
        container: qc.lic_sickly-auburn-cuscus
  QC.Met:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-amethyst-chameleon.sh
        container: qc.met_thirsty-charcoal-capybara
  QC.Sec:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-yellow-dunker.sh
        container: qc.sec_surly-bronze-zonkey
  QC.Sty:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-tangerine-chicken.sh
        container: qc.sty_wimpy-pumpkin-zonkey
      github.com/interTwin-eu/hython-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-apricot-spoonbill.sh
        container: qc.sty_hasty-myrtle-stoat
      github.com/interTwin-eu/hython-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-seashell-ray.sh
        container: qc.sty_messy-cream-bullfrog
  QC.Uni:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.ready-heliotrope-wolverine.sh
        container: qc.uni_wheezy-auburn-shrew
  QC.Ver:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-brass-penguin.sh
        container: qc.ver_skinny-amethyst-axolotl
timeout: 5400
