config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/hython-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/hython-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-heliotrope-kiwi.sh
        container: qc.acc_lumpy-white-tapir
  QC.Doc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-thistle-beaver.sh
        container: qc.doc_snazzy-olive-chinchilla
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-viridian-axolotl.sh
        container: qc.doc_lousy-saffron-lemming
      github.com/interTwin-eu/hython-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-firebrick-sponge.sh
        container: qc.doc_lousy-platinum-robin
  QC.Lic:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-green-pig.sh
        container: qc.lic_thirsty-carmine-pig
  QC.Met:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-bistre-mongrel.sh
        container: qc.met_ready-platinum-setter
  QC.Sec:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-ultramarine-wolverine.sh
        container: qc.sec_ugly-violet-coati
  QC.Sty:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-pumpkin-fly.sh
        container: qc.sty_gummy-olivine-sheepdog
      github.com/interTwin-eu/hython-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-magnolia-weasel.sh
        container: qc.sty_clammy-zucchini-grouse
      github.com/interTwin-eu/hython-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-vermilion-loon.sh
        container: qc.sty_snazzy-coral-tapir
  QC.Uni:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-pink-butterfly.sh
        container: qc.uni_woolly-apricot-eleuth
  QC.Ver:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-heliotrope-deer.sh
        container: qc.ver_nerdy-cerise-leopard
timeout: 5400
