config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/hython-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/hython-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-tangerine-chow.sh
        container: qc.acc_slimy-chocolate-cheetah
  QC.Doc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-charcoal-urchin.sh
        container: qc.doc_smelly-amethyst-swan
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-thistle-frise.sh
        container: qc.doc_muzzy-linen-mist
      github.com/interTwin-eu/hython-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-rust-cassowary.sh
        container: qc.doc_squirrely-cobalt-horse
  QC.Lic:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-razzmatazz-hornet.sh
        container: qc.lic_messy-goldenrod-weasel
  QC.Met:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-silver-barb.sh
        container: qc.met_baggy-asparagus-boar
  QC.Sec:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-orange-beaver.sh
        container: qc.sec_gummy-apricot-kingfisher
  QC.Sty:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-denim-hornet.sh
        container: qc.sty_foggy-firebrick-alligator
      github.com/interTwin-eu/hython-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-crimson-mau.sh
        container: qc.sty_crappy-persimmon-peccary
      github.com/interTwin-eu/hython-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-taupe-wrasse.sh
        container: qc.sty_frumpy-auburn-falcon
  QC.Uni:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-fuchsia-fossa.sh
        container: qc.uni_breezy-sangria-bonobo
  QC.Ver:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-charcoal-bracke.sh
        container: qc.ver_silly-silver-tuatara
timeout: 5400
