config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/hython-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/hython-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-myrtle-cockroach.sh
        container: qc.acc_silly-firebrick-cichlid
  QC.Doc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-beige-stingray.sh
        container: qc.doc_stuffy-amber-monster
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-apricot-deer.sh
        container: qc.doc_homey-plum-devil
      github.com/interTwin-eu/hython-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-malachite-uakari.sh
        container: qc.doc_gamy-flax-moose
  QC.Lic:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-red-rat.sh
        container: qc.lic_geeky-ochre-corgi
  QC.Met:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-russet-bracke.sh
        container: qc.met_sleepy-khaki-kingfisher
  QC.Sec:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-amaranth-insect.sh
        container: qc.sec_silly-mauve-nightingale
  QC.Sty:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-wisteria-seal.sh
        container: qc.sty_lanky-beige-audemer
      github.com/interTwin-eu/hython-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-charcoal-chimpanzee.sh
        container: qc.sty_slimy-champagne-horse
      github.com/interTwin-eu/hython-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-gold-dogfish.sh
        container: qc.sty_ready-rust-wildebeest
  QC.Uni:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-turquoise-bulldog.sh
        container: qc.uni_shaggy-violet-ladybird
  QC.Ver:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-orchid-chicken.sh
        container: qc.ver_chummy-alizarin-vole
timeout: 5400
