config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/hython-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/hython-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-bronze-llama.sh
        container: qc.acc_snippy-dandelion-ocelot
  QC.Doc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-red-chimpanzee.sh
        container: qc.doc_craggy-saffron-beetle
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-flax-insect.sh
        container: qc.doc_leaky-chestnut-zebra
      github.com/interTwin-eu/hython-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-zucchini-bat.sh
        container: qc.doc_nerdy-dandelion-scorpion
  QC.Lic:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-lavender-uakari.sh
        container: qc.lic_baggy-pink-elephant
  QC.Met:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-puce-audemer.sh
        container: qc.met_droopy-ecru-binturong
  QC.Sec:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-myrtle-hound.sh
        container: qc.sec_seedy-mustard-akita
  QC.Sty:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-alizarin-centipede.sh
        container: qc.sty_scaly-wisteria-scorpion
      github.com/interTwin-eu/hython-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-mauve-snail.sh
        container: qc.sty_woozy-orchid-turtle
      github.com/interTwin-eu/hython-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-dandelion-kakapo.sh
        container: qc.sty_sloppy-puce-flamingo
  QC.Uni:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-tangerine-wolf.sh
        container: qc.uni_hasty-lime-robin
  QC.Ver:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-scarlet-goat.sh
        container: qc.ver_squirrely-sepia-albatross
timeout: 5400
