config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/hython-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/hython-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-apricot-antelope.sh
        container: qc.acc_sloppy-pumpkin-russel
  QC.Doc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-tangerine-weasel.sh
        container: qc.doc_thirsty-myrtle-mule
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-lemon-rattlesnake.sh
        container: qc.doc_stinky-lavender-gibbon
      github.com/interTwin-eu/hython-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-ruby-tuatara.sh
        container: qc.doc_snazzy-amethyst-argentino
  QC.Lic:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-firebrick-bordeaux.sh
        container: qc.lic_nerdy-lemon-sheep
  QC.Met:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-pear-crab.sh
        container: qc.met_wimpy-cinnabar-caracal
  QC.Sec:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-lilac-duck.sh
        container: qc.sec_shabby-khaki-gharial
  QC.Sty:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-amaranth-squirt.sh
        container: qc.sty_randy-bistre-monster
      github.com/interTwin-eu/hython-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-ivory-mayfly.sh
        container: qc.sty_snoopy-harlequin-buffalo
      github.com/interTwin-eu/hython-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-brown-javanese.sh
        container: qc.sty_bluesy-cinnamon-anteater
  QC.Uni:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-burgundy-alligator.sh
        container: qc.uni_gamy-tomato-setter
  QC.Ver:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-tomato-tarantula.sh
        container: qc.ver_snoopy-ultramarine-squirt
timeout: 5400
