config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/hython-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/hython-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-fuchsia-urchin.sh
        container: qc.acc_flaky-grey-toad
  QC.Doc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-black-hedgehog.sh
        container: qc.doc_droopy-fuchsia-tamarin
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-turquoise-mayfly.sh
        container: qc.doc_homely-eggplant-monkey
      github.com/interTwin-eu/hython-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-cerise-dormouse.sh
        container: qc.doc_snazzy-myrtle-camel
  QC.Lic:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-orchid-robin.sh
        container: qc.lic_homey-lemon-albatross
  QC.Met:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-mauve-buffalo.sh
        container: qc.met_skinny-apricot-ragdoll
  QC.Sec:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-celadon-pig.sh
        container: qc.sec_wheezy-charcoal-mist
  QC.Sty:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-cyan-affenpinscher.sh
        container: qc.sty_slimy-amethyst-oriole
      github.com/interTwin-eu/hython-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-pear-insect.sh
        container: qc.sty_shaggy-taupe-catfish
      github.com/interTwin-eu/hython-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-goldenrod-axolotl.sh
        container: qc.sty_trippy-dandelion-zorse
  QC.Uni:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-green-dogfish.sh
        container: qc.uni_crappy-saffron-crocodile
  QC.Ver:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-bronze-turtle.sh
        container: qc.ver_silly-auburn-skunk
timeout: 5400
