config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/hython-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/hython-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-chartreuse-caracal.sh
        container: qc.acc_boozy-azure-tetra
  QC.Doc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-charcoal-skunk.sh
        container: qc.doc_gamy-celadon-tortoise
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-chocolate-tzu.sh
        container: qc.doc_ugly-orange-husky
      github.com/interTwin-eu/hython-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-celadon-weasel.sh
        container: qc.doc_muggy-brown-mandrill
  QC.Lic:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-salmon-spaniel.sh
        container: qc.lic_zippy-periwinkle-antelope
  QC.Met:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-xanthic-serval.sh
        container: qc.met_crabby-amaranth-moorhen
  QC.Sec:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-cardinal-tapir.sh
        container: qc.sec_jumpy-turquoise-rabbit
  QC.Sty:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.messy-gold-barnacle.sh
        container: qc.sty_flaky-orange-cuscus
      github.com/interTwin-eu/hython-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-coral-ferret.sh
        container: qc.sty_paltry-orange-quail
      github.com/interTwin-eu/hython-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-cream-earwig.sh
        container: qc.sty_nerdy-puce-gecko
  QC.Uni:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-azure-boar.sh
        container: qc.uni_grumpy-zucchini-dogfish
  QC.Ver:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-linen-dodo.sh
        container: qc.ver_lumpy-yellow-impala
timeout: 5400
