config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/hython-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/hython-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-bronze-kudu.sh
        container: qc.acc_shaggy-ultramarine-dollar
  QC.Doc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-purple-rhinoceros.sh
        container: qc.doc_grumpy-brass-lemming
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-crimson-dalmatian.sh
        container: qc.doc_sloppy-cinnabar-coral
      github.com/interTwin-eu/hython-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-plum-bison.sh
        container: qc.doc_cranky-sangria-ibis
  QC.Lic:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-carmine-civet.sh
        container: qc.lic_cloudy-denim-tzu
  QC.Met:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-khaki-fossa.sh
        container: qc.met_nerdy-maroon-whippet
  QC.Sec:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-dandelion-deer.sh
        container: qc.sec_snazzy-pink-frise
  QC.Sty:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-buff-vulture.sh
        container: qc.sty_clammy-eggplant-chipmunk
      github.com/interTwin-eu/hython-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-thistle-crab.sh
        container: qc.sty_flabby-maroon-macaque
      github.com/interTwin-eu/hython-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-olivine-stingray.sh
        container: qc.sty_clammy-lemon-gibbon
  QC.Uni:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-wisteria-wrasse.sh
        container: qc.uni_snappy-razzmatazz-warthog
  QC.Ver:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-jade-worm.sh
        container: qc.ver_bumpy-tangerine-angora
timeout: 5400
