config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/hython-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/hython-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-charcoal-dollar.sh
        container: qc.acc_shaky-carmine-cow
  QC.Doc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-plum-burmese.sh
        container: qc.doc_whiny-brown-balinese
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-black-badger.sh
        container: qc.doc_gummy-black-insect
      github.com/interTwin-eu/hython-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-harlequin-caiman.sh
        container: qc.doc_queasy-razzmatazz-macaw
  QC.Lic:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-lemon-wrasse.sh
        container: qc.lic_sleepy-yellow-impala
  QC.Met:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-khaki-mouse.sh
        container: qc.met_snoopy-khaki-tarsier
  QC.Sec:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-ruby-mayfly.sh
        container: qc.sec_scaly-ruby-stingray
  QC.Sty:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-green-capybara.sh
        container: qc.sty_stinky-puce-lobster
      github.com/interTwin-eu/hython-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-maroon-barracuda.sh
        container: qc.sty_whiny-apricot-tetra
      github.com/interTwin-eu/hython-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-bistre-dolphin.sh
        container: qc.sty_hazy-grey-frog
  QC.Uni:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.homely-cerise-rabbit.sh
        container: qc.uni_stealthy-buff-bobcat
  QC.Ver:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-ochre-fish.sh
        container: qc.ver_frumpy-gamboge-cuscus
timeout: 5400
