config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/hython-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/hython-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-brass-tarantula.sh
        container: qc.acc_chummy-cerise-butterfly
  QC.Doc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-cyan-terrier.sh
        container: qc.doc_cranky-sepia-frise
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-bronze-ladybird.sh
        container: qc.doc_crabby-wheat-bonobo
      github.com/interTwin-eu/hython-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-seashell-wolverine.sh
        container: qc.doc_lousy-platinum-chinchilla
  QC.Lic:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-burgundy-yak.sh
        container: qc.lic_shaky-aqua-booby
  QC.Met:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.homey-azure-kakapo.sh
        container: qc.met_bluesy-cinnabar-horse
  QC.Sec:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.homely-magnolia-newt.sh
        container: qc.sec_woozy-alizarin-havanese
  QC.Sty:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-platinum-panda.sh
        container: qc.sty_messy-linen-leopard
      github.com/interTwin-eu/hython-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-linen-bandicoot.sh
        container: qc.sty_scummy-sangria-civet
      github.com/interTwin-eu/hython-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-azure-magpie.sh
        container: qc.sty_tacky-wisteria-sparrow
  QC.Uni:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-denim-quetzal.sh
        container: qc.uni_sleepy-pear-greyhound
  QC.Ver:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-denim-shark.sh
        container: qc.ver_bumpy-bronze-audemer
timeout: 5400
