config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/hython-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/hython-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-aqua-stoat.sh
        container: qc.acc_scummy-lavender-toucan
  QC.Doc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-cinnamon-shark.sh
        container: qc.doc_baggy-khaki-cockroach
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-ivory-pinscher.sh
        container: qc.doc_woolly-apricot-collie
      github.com/interTwin-eu/hython-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-tan-cat.sh
        container: qc.doc_flimsy-goldenrod-snail
  QC.Lic:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-pumpkin-hyena.sh
        container: qc.lic_hilly-ultramarine-insect
  QC.Met:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-maroon-olm.sh
        container: qc.met_cloudy-khaki-grasshopper
  QC.Sec:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-violet-giraffe.sh
        container: qc.sec_muzzy-mauve-impala
  QC.Sty:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ready-magenta-caiman.sh
        container: qc.sty_cloudy-burgundy-earwig
      github.com/interTwin-eu/hython-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-asparagus-rattlesnake.sh
        container: qc.sty_baggy-copper-ferret
      github.com/interTwin-eu/hython-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-black-chin.sh
        container: qc.sty_woozy-sangria-flamingo
  QC.Uni:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-celadon-tamarin.sh
        container: qc.uni_muggy-fuchsia-nightingale
  QC.Ver:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-auburn-setter.sh
        container: qc.ver_scaly-lemon-woodlouse
timeout: 5400
