config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/hython-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/hython-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-wisteria-foxhound.sh
        container: qc.acc_paltry-ecru-uakari
  QC.Doc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-magnolia-echidna.sh
        container: qc.doc_grumpy-ivory-russel
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-seashell-chin.sh
        container: qc.doc_wheezy-white-iguana
      github.com/interTwin-eu/hython-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-russet-civet.sh
        container: qc.doc_sunny-auburn-bongo
  QC.Lic:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-rose-meerkat.sh
        container: qc.lic_thirsty-cyan-opossum
  QC.Met:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-chestnut-flounder.sh
        container: qc.met_gimpy-ivory-kangaroo
  QC.Sec:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-gamboge-quail.sh
        container: qc.sec_randy-aquamarine-wasp
  QC.Sty:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-goldenrod-akita.sh
        container: qc.sty_lanky-pink-chicken
      github.com/interTwin-eu/hython-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-pink-woodlouse.sh
        container: qc.sty_gloppy-apricot-caracal
      github.com/interTwin-eu/hython-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-corn-chin.sh
        container: qc.sty_seedy-cinnamon-paradise
  QC.Uni:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-flax-jaguar.sh
        container: qc.uni_seedy-gamboge-boar
  QC.Ver:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-gamboge-catfish.sh
        container: qc.ver_thirsty-smalt-capuchin
timeout: 5400
