config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/hython-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/hython-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-tangerine-yak.sh
        container: qc.acc_flimsy-burgundy-wildebeest
  QC.Doc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-plum-capuchin.sh
        container: qc.doc_lousy-cyan-rottweiler
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-charcoal-rattlesnake.sh
        container: qc.doc_tasty-taupe-crab
      github.com/interTwin-eu/hython-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-maroon-zebu.sh
        container: qc.doc_droopy-magnolia-cockroach
  QC.Lic:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-magenta-lion.sh
        container: qc.lic_homely-alizarin-dunker
  QC.Met:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-mustard-moth.sh
        container: qc.met_ready-amethyst-goose
  QC.Sec:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-coral-mandrill.sh
        container: qc.sec_cozy-purple-bee
  QC.Sty:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-magnolia-cichlid.sh
        container: qc.sty_goopy-brass-schnauzer
      github.com/interTwin-eu/hython-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-russet-flounder.sh
        container: qc.sty_bluesy-white-fox
      github.com/interTwin-eu/hython-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-flax-sparrow.sh
        container: qc.sty_paltry-alizarin-clam
  QC.Uni:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-wheat-pinscher.sh
        container: qc.uni_craggy-peach-catfish
  QC.Ver:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-chestnut-crab.sh
        container: qc.ver_woozy-green-drever
timeout: 5400
