config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/hython-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/hython-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-aquamarine-drever.sh
        container: qc.acc_slimy-green-sloth
  QC.Doc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-brass-lizard.sh
        container: qc.doc_queasy-tan-argentino
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-magnolia-tapir.sh
        container: qc.doc_snazzy-mauve-grouse
      github.com/interTwin-eu/hython-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-burgundy-lionfish.sh
        container: qc.doc_pasty-indigo-tuatara
  QC.Lic:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-firebrick-wasp.sh
        container: qc.lic_chummy-cardinal-millipede
  QC.Met:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-alizarin-bee.sh
        container: qc.met_scaly-maroon-javanese
  QC.Sec:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-brass-newfoundland.sh
        container: qc.sec_cheeky-grey-chinchilla
  QC.Sty:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-amethyst-dolphin.sh
        container: qc.sty_baggy-apricot-lynx
      github.com/interTwin-eu/hython-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-purple-mole.sh
        container: qc.sty_queasy-emerald-crab
      github.com/interTwin-eu/hython-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-carmine-hare.sh
        container: qc.sty_paltry-harlequin-ferret
  QC.Uni:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-pink-tarantula.sh
        container: qc.uni_snippy-plum-shrimp
  QC.Ver:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-cobalt-chinook.sh
        container: qc.ver_sickly-lemon-schnauzer
timeout: 5400
