config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/hython-itwinai-plugin:
      branch: main
      repo: https://github.com/interTwin-eu/hython-itwinai-plugin
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-cerulean-angelfish.sh
        container: qc.acc_wheezy-wheat-wolverine
  QC.Doc:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-cinnabar-rat.sh
        container: qc.doc_queasy-cornflower-sheepdog
      github.com/interTwin-eu/hython-itwinai-plugin git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-maroon-toad.sh
        container: qc.doc_stealthy-harlequin-foxhound
      github.com/interTwin-eu/hython-itwinai-plugin markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-beige-toucan.sh
        container: qc.doc_tasty-emerald-skunk
  QC.Lic:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-salmon-nightingale.sh
        container: qc.lic_trippy-ultramarine-gibbon
  QC.Met:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-denim-kingfisher.sh
        container: qc.met_boozy-harlequin-buzzard
  QC.Sec:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin bandit:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-buff-duck.sh
        container: qc.sec_thirsty-razzmatazz-newfoundland
  QC.Sty:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-cinnamon-gar.sh
        container: qc.sty_cozy-xanthic-labradoodle
      github.com/interTwin-eu/hython-itwinai-plugin hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-wheat-dugong.sh
        container: qc.sty_shaky-aquamarine-reindeer
      github.com/interTwin-eu/hython-itwinai-plugin jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-emerald-harrier.sh
        container: qc.sty_cozy-firebrick-dugong
  QC.Uni:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin commands:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-plum-fish.sh
        container: qc.uni_chummy-buff-quokka
  QC.Ver:
    repos:
      github.com/interTwin-eu/hython-itwinai-plugin get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-viridian-beagle.sh
        container: qc.ver_chewy-lime-hound
timeout: 5400
